#!/usr/bin/python

from roscompile.package import get_packages
from roscompile.main import roscompile
from roscompile.config import CFG

CFG.check_command_flags()
pkgs = get_packages()
roscompile(pkgs)
CFG.write()
